---
services:
  mybb:
    build:
      context: ./docker
      dockerfile: ../mybb_8.2.Dockerfile
      args:
        BUILD_VERSION: 1838
        BUILD_SHA512SUM: ccf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e
        BUILD_AUTHORS: anonymous
        BUILD_DATE: dontcare
    volumes:
      - ${PWD}/wwwroot:/var/www/html:rw
      - ${PWD}/conf/config.php:/var/www/html/inc/config.php:ro
      - ${PWD}/conf/lock:/var/www/html/install/lock:ro

  nginx:
    image: nginx:mainline-alpine
    ports:
      - published: 8080
        target: 80
    volumes:
      - ${PWD}/conf/nginx_mybb.conf:/etc/nginx/conf.d/default.conf:ro
      - ${PWD}/wwwroot:/var/www/html:ro

  mariadb:
    image: mariadb:11.3
    environment:
      MARIADB_ROOT_PASSWORD: changeme
      MARIADB_DATABASE: mybb
    volumes:
      - ${PWD}/conf/initial_with_pms.sql:/docker-entrypoint-initdb.d/99-init.sql:ro

  phpmyadmin:
    image: phpmyadmin:5
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: changeme
    ports:
      - published: 8081
        target: 80

